package com.beeswork.balance.internal.constant

const val CURRENT_FCM_TOKEN_ID = 1

const val MIN_CARD_STACK_SIZE = 15

const val LOCATION_REQUEST_INTERVAL = 5000L
const val LOCATION_REQUEST_FASTEST_INTERVAL = 5000L

const val NETWORK_READ_TIMEOUT = 100L
const val NETWORK_CONNECTION_TIMEOUT = 100L

const val CHAT_PAGE_SIZE = 30
const val CHAT_PAGE_PREFETCH_DISTANCE = CHAT_PAGE_SIZE * 2
const val CHAT_MAX_PAGE_SIZE = CHAT_PAGE_PREFETCH_DISTANCE * 2 + CHAT_PAGE_SIZE

const val MATCH_PAGE_SIZE = 30
const val MATCH_PAGE_PREFETCH_DISTANCE = MATCH_PAGE_SIZE * 2
const val MATCH_MAX_PAGE_SIZE = MATCH_PAGE_PREFETCH_DISTANCE * 2 + MATCH_PAGE_SIZE



const val CLICKED_PAGE_SIZE = 15
const val CLICKED_PAGE_PREFETCH_DISTANCE = CLICKED_PAGE_SIZE * 2
const val CLICKED_MAX_PAGE_SIZE = CLICKED_PAGE_PREFETCH_DISTANCE * 2 + CLICKED_PAGE_SIZE