package com.beeswork.balance.internal.constant

const val CURRENT_FCM_TOKEN_ID = 1
const val MIN_CARD_STACK_SIZE = 15
const val LOCATION_REQUEST_INTERVAL = 5000L
const val LOCATION_REQUEST_FASTEST_INTERVAL = 5000L
const val NETWORK_READ_TIMEOUT = 10L
const val NETWORK_CONNECTION_TIMEOUT = 10L